###
GET localhost:3000/api/post/

###
POST localhost:3000/api/post/
Content-Type: application/json

{
  "title": "23,测试文章标题",
  "content": "test2",
  "author": "test",
  "type": 0
}

###
GET localhost:3000/api/post/1
